<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-14T11:50:36 IST" name="Default suite" finished-at="2024-02-14T11:51:10 IST" duration-ms="34222">
    <groups>
    </groups>
    <test started-at="2024-02-14T11:50:36 IST" name="Default test" finished-at="2024-02-14T11:51:10 IST" duration-ms="34222">
      <class name="com.truboardpartners.testClasses.Developer_ProjectSetUp">
        <test-method is-config="true" signature="suiteSetup()[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c]" started-at="2024-02-14T11:50:36 IST" name="suiteSetup" finished-at="2024-02-14T11:50:36 IST" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetup -->
        <test-method is-config="true" signature="startReporting(java.lang.reflect.Method)[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c]" started-at="2024-02-14T11:50:36 IST" name="startReporting" finished-at="2024-02-14T11:50:39 IST" duration-ms="3300" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.truboardpartners.testClasses.Developer_ProjectSetUp.raiseNOCRequest() throws java.awt.AWTException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReporting -->
        <test-method signature="raiseNOCRequest()[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c]" started-at="2024-02-14T11:50:39 IST" name="raiseNOCRequest" description="Developer raise NOC request" finished-at="2024-02-14T11:51:10 IST" duration-ms="30880" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Validation of Logout button for login]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Validation of Logout button for login
at org.testng.Assert.fail(Assert.java:99)
at com.turbopartners.pom.pages.LoginPage.loginDeveloper(LoginPage.java:45)
at com.truboardpartners.testClasses.Developer_ProjectSetUp.raiseNOCRequest(Developer_ProjectSetUp.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- raiseNOCRequest -->
        <test-method is-config="true" signature="testResult(java.lang.reflect.Method,org.testng.ITestResult)[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c]" started-at="2024-02-14T11:51:10 IST" name="testResult" finished-at="2024-02-14T11:51:10 IST" duration-ms="0" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.truboardpartners.testClasses.Developer_ProjectSetUp.raiseNOCRequest() throws java.awt.AWTException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=raiseNOCRequest status=FAILURE method=Developer_ProjectSetUp.raiseNOCRequest()[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Validation of Logout button for login expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Validation of Logout button for login expected [1] but found [0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.truboard.framework.BaseTest.testResult(BaseTest.java:128)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResult -->
        <test-method is-config="true" signature="generateResult()[pri:0, instance:com.truboardpartners.testClasses.Developer_ProjectSetUp@2767e23c]" started-at="2024-02-14T11:51:10 IST" name="generateResult" finished-at="2024-02-14T11:51:11 IST" duration-ms="408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateResult -->
      </class> <!-- com.truboardpartners.testClasses.Developer_ProjectSetUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
